name: Docker Build CI

on:
  push:
    branches: [ master ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Get commit info
        run: |
          echo "::set-env name=head::$(git log -1 HEAD --pretty=format:%s)"
          echo "::set-env name=body::$(git log -1 HEAD --pretty=format:%b)" 
      - name: Tweet update
        uses: Z-M-Huang/TweetOnAction@v1
        with:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
          token_secret: ${{ secrets.TOKEN_SECRET }}
          content: "New commit for ${{ github.repository}}\n${{ env.head }}\n${{ env.body }}. Send tweet on GithubAction. Checkout it out at: https://github.com/Z-M-Huang/TweetOnAction"